clone_depth: 5

install:
  - node --version
  - npm --version
  - npm install

build_script:
  - npm run build

test_script:
  - npm test

artifacts:
  - path: build

on_success:
  - IF %APPVEYOR_REPO_TAG% EQU true (echo 0) ELSE (echo 1)